### ISSUE TITLE
Find helpers for reproducibility workshop

### ISSUE THREAD

**Issue by bvreede** [Rbanism/Rbanism#10]
And perhaps use ngrok for live coding? https://bitsandbricks.github.io/post/code-live-from-rstudio-and-share-it-with-the-world-in-real-time/

**Comment by cforgaci** [comment]
Good news. Aleksandra Wilczynska and Ashley Cryan from the TU Delft DCC & R Café accepted to join.

**Comment by cforgaci** [comment]
Bjørn Bartholdy can also join for a half day if needed.

**Comment by cforgaci** [comment]
I think helpers are covered

**Comment by cforgaci** [comment]
@bvreede, my colleagues from the TU Delft DCC have tested and chosen a solution for live coding. We are planning to use it in the next Data Carpentry workshop. The chosen solution uses gitautopush and the steps are the following:
-  `pip install gitautopush`
-  crate an empty repository on GitHub
-  clone  the repository to your local directory
-  in terminal, start observing the folder by command: `gitautopush /path/to/my/repo/folder`
-  in the folder of the repository, create a new R script or R Markdown (or any other file that will be pushed) and save the changes
-  see if it automatically pushes to the repository.
 
This works for me nicely.
