### ISSUE TITLE
Invite a speaker from the ReproHack community  for an inspirational lecture

### ISSUE THREAD

**Issue by bvreede** [Rbanism/Rbanism#4]
- anna krystalli?
- One of the authors of [this paper](https://www.tandfonline.com/doi/pdf/10.1080/14498596.2019.1654944)?

**Comment by cforgaci** [comment]
Hugo Ledoux invited and confirmed

**Comment by cforgaci** [comment]
Or should we still invite Daniela or someone from the ReproHack community to say a few words (5 minutes) about ReproHack? This person can join online. Would that be useful?
