### ISSUE TITLE
Prepare download package for participants

### ISSUE THREAD

**Issue by cforgaci** [Rbanism/Rbanism#40]
- [x] List the files needed for each part of the workshop
- [x] Prepare an archive the files to be sent out to participants

## File list (from the download package README)

-   `data/gapminder_5060.csv`, `data/gapminder_7080.csv`, `data/gapminder_90plus.csv`: demo Gapminder data used in the introduction
-   `data/gapminderDataFiveYear.tsv`: the cleaned and subset version of the Gapminder dataset available from the [gapminder R package](http://github.com/jennybc/gapminder).
-   `data/urban_population.csv`: a subset version of the Gapminder dataset.
-   `documents/countryPick.Rmd`: R Markdown file demonstrating various features of literate programming with R.
-   `documents/intro-demo.Rmd`: demo R Markdown file used in the introduction.
-   `documents/checklist.md`: reproducibility checklist compiled for the Rbanism project from various sources.
-   `R/`: an empty folder in which R scripts will be added during the workshop.

**Comment by cforgaci** [comment]
@bvreede, I created a download package including folders, documents and data used across our lessons. For you, I added `data/urban_population.csv`. Is that all?

**Comment by bvreede** [comment]
Thanks! I will do a tiny bit of fudging, since a big part of my lesson will be to create a good folder structure, so e.g. they will not need a pre-made R folder. I will leave the rest intact though, and create a new zip file to be downloaded.

**Comment by bvreede** [comment]
Closed with https://github.com/Rbanism/repro-r-workshop/commit/1f30e1546673a24bf9140ca531aa1b2f2ad483c0
