### ISSUE TITLE
Workshop repository organisation

### ISSUE THREAD

**Issue by cforgaci** [Rbanism/Rbanism#41]
File organisation in the workshop repository:
- `data\` - All data used throughout the workshop
- `documents\` - All `Rmd` and `md` files
- `R\` - The R script(s) used in the automation part of the workshop
- `download\` - This folder holds a copy of the `data\`, `documents\` and `R\` folders only containing the files that the participants need to follow the workshop
- `repro-r-workshop.zip` - an archive of the `download\` folder that the participants can download unzip and start using as their project folder during the workshop - see also #40

**Comment by cforgaci** [comment]
@bvreede can you move your documents from `exercises/` to `documents/`, please? I created a folder structure as we agreed on Wednesday. And please use the file naming pattern of the other lessons. Thanks!

**Comment by bvreede** [comment]
Thanks, done! Closing this issue :)
