### ISSUE TITLE
Prepare live code repository

### ISSUE THREAD

**Issue by cforgaci** [Rbanism/Rbanism#43]

**Comment by cforgaci** [comment]
@bvreede, I prepared the live code repository for gitautopush as follows: 

1. I added to the repro-r-workshop-livecode repository the exact files and folders that the participants will get from our download package.
2. In the README I added the links to the file I will create in the literate programming part. As soon as the file is created (I am demonstrating the file creation too), the relative link will start working and the participants can use it to copy-paste. 

Two small things for you here:

- [x] Does the organisation part involve live code? If not, feel free to erase that line from the README.
- [x] Please add the name of and link to the R script you will create in the automation part.

**Comment by bvreede** [comment]
Thanks! Looks fab!
