### ISSUE TITLE
How to attract submissions to the Reproducibility challenge?

### ISSUE THREAD

**Issue by cforgaci** [Rbanism/Rbanism#47]
For the initial deadline, the Challenge only received on submission. Now that the deadline is extended by two more months, it is also important that the community receives reminders and stimuli to submit. What is the best way to do this?

**Comment by bvreede** [comment]
- Powerpoint template
- Quotes or questions
- Link to description

**Comment by bvreede** [comment]
If you would open your Master's project today, could you reproduce your work?

**Comment by bvreede** [comment]
Do you trust your past self?

**Comment by cforgaci** [comment]
Is your research a black box?

**Comment by bvreede** [comment]
import PhDthesis

PhDthesis.run()

**Comment by bvreede** [comment]
We all make mistakes. Share them.

**Comment by bvreede** [comment]
Sharing is caring.

**Comment by cforgaci** [comment]
It's ok to be proud of your code and data

**Comment by bvreede** [comment]
Is reproducibility really a challenge?

**Comment by bvreede** [comment]
... is good.
Reproducibility is better.

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/204796299-711b4d08-0d7b-4a14-863a-f7c73e00fc12.png)

**Comment by cforgaci** [comment]
RbanismChallenge::reproduce(my_work)

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/204796937-7e2b38aa-c93e-45c3-99bd-64998e7e8ee4.png)

**Comment by cforgaci** [comment]
Is your research well documented?

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/204797259-3893a7f9-7232-4d13-a05f-555573ec7ea1.png)

**Comment by cforgaci** [comment]
![Image](https://user-images.githubusercontent.com/33600128/204797287-1787d63e-d0cf-48d0-8f57-c2858761c0ed.png)

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/204797802-8f1257aa-bb4e-465d-a4a0-5b0773382109.png)

**Comment by bvreede** [comment]
or...

![image](https://user-images.githubusercontent.com/5747405/204798098-df3191bc-0a3e-498c-b399-2943a3da371d.png)

**Comment by cforgaci** [comment]
![Image](https://user-images.githubusercontent.com/33600128/204798406-68b0f506-5345-4eb2-b88e-e89f5ab6d117.png)

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/204798428-d3e85975-f4f9-4ebd-80a5-5ddee1f00b7a.png)

**Comment by cforgaci** [comment]
Imagine a world without cookbooks!

**Comment by cforgaci** [comment]
![](https://memecreator.org/static/images/memes/5529057.jpg)

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/204799460-9c817291-3985-4518-a5e0-1daa9108f803.png)

**Comment by cforgaci** [comment]
![](https://memecreator.org/static/images/memes/5398861.jpg)

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/204801063-35de2a00-0495-4db7-b1fb-20c68773682c.png)

**Comment by cforgaci** [comment]
Challenge ended. Closing this issue.
