### ISSUE TITLE
Find someone for an inspirational story during the workshop

### ISSUE THREAD

**Issue by bvreede** [Rbanism/Rbanism#6]
- related to geospatial research (preferably urbanism)
- someone from escience center?
- brief, inspirational!
- to kick off the workshop

**Comment by cforgaci** [comment]
[Hugo Ledoux](https://3d.bk.tudelft.nl/hledoux/) accepted the invitation. He is from the 3D Geoinformation in my department, a computer scientist with a lot of experience with reproducibility but also knowledge of the domain of urbanism.
