### ISSUE TITLE
Set up work environment for Rbanism website

### ISSUE THREAD

**Issue by cforgaci** [Rbanism/Rbanism#68]
- [x] Install R and R Studio: https://posit.co/downloads/
- [x] Install Quarto: https://quarto.org/docs/get-started/
- [x] Create RStudio project with Rbanism repo

**Comment by DimitrisMantas** [comment]
Done.

**Comment by cforgaci** [comment]
@DimitrisMantas, good! Please check the three checkboxes if you did all three and close the issue.

**Comment by DimitrisMantas** [comment]
@cforgaci I don't have permission to assign people to cards, or close issues not created by myself. I had it on the agenda for Wednesday.

**Comment by DimitrisMantas** [comment]
The same issue holds for editing comments created by others.

**Comment by DimitrisMantas** [comment]
Done.
