### ISSUE TITLE
Rbanism community management work environment

### ISSUE THREAD

**Issue by DimitrisMantas** [Rbanism/Rbanism#70]
- [x] Create MS Teams environment
- [x] Move the list of community members from Google docs to MS Teams
- [x] Check integrations between GitHub, Slack, MS Teams
- [x] Check what Slack functionalities we need and if we need a paid version

**Comment by DimitrisMantas** [comment]
- Added MS Forms to our team's [worskpace](https://teams.microsoft.com/l/team/19%3afL-Y4DIWTyZgAIzxJt2Ri-FzcDDZDU0yWWpoFy9IgB81%40thread.tacv2/conversations?groupId=b7aeb01a-a938-4a97-8119-67786788bf53&tenantId=096e524d-6929-4030-8cd3-8ab42de0887b) in MS Teams.
- Copied the list of community members from Google Drive to MS Teams. Click [here](https://tud365.sharepoint.com/:x:/r/sites/Rbanism/Gedeelde%20documenten/General/Contacts.xlsx?d=w525d2b587b2e490584a0d19fa5d44669&csf=1&web=1&e=18Fqwb) to view.

**Comment by DimitrisMantas** [comment]
- Checked Slack pricing. We need at least the Pro version ($6.75/m) in order to have unlimited message history. Click [here](https://slack.com/pricing) for more information.

**Comment by DimitrisMantas** [comment]
- Checked GitHub, Teams, and Slack integration. We can move away from Slack completely and only work using Teams and GitHub. Click [here](https://learn.microsoft.com/en-us/microsoftteams/migrate-slack-to-teams) for more information.

**Comment by DimitrisMantas** [comment]
We are still pending the approval of the GitHub app for Teams.

**Comment by cforgaci** [comment]
Done.
