### ISSUE TITLE
Community mailing list

### ISSUE THREAD

**Issue by cforgaci** [Rbanism/Rbanism#72]
- [x] finalise the registration form
- [x] ask members who are in our database to fill in the form
- [x] Claudiu, Clémentine and Daniele check test cases on how the registration form could break

**Comment by DimitrisMantas** [comment]
Test Cases
-----------

- Check what happens if a question that already has answers gets deleted.
    - ***EVERYTHING*** gets deleted.

**Comment by DimitrisMantas** [comment]
Reviewed the form. It's now pending @cforgaci's approval.

**Comment by cforgaci** [comment]
The tasks in this issue have been carried out.
