### ISSUE TITLE
R reproducibility workshop: automation

### ISSUE THREAD

**Issue by bvreede** [Rbanism/Rbanism#8]
- [ ] Clean up data
- [ ] Write an R workflow from data to analysis and visualization
- [ ] Include file download, either in workflow or in Setup

**Comment by cforgaci** [comment]
workflow with gapminder data in the rr carpentry lesson: https://github.com/datacarpentry/rr-intro/tree/gh-pages/intro

**Comment by cforgaci** [comment]
broadcasted live coding (instead of having a note taker): https://www.youtube.com/watch?v=idFpvvH1JyI&ab_channel=TheCarpentries
